name: livelovehelsinki
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5945223020389676
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060900'
    - '#f2f2f2'
    - '#178fd3'
    - '#7bb8e6'
    - '#3c4207'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
